[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 